### PR TITLE
Barbz yhool group handler

### PR DESCRIPTION
**Pull request by dunjeon**
##### CHANGES PROPOSED:

-  
-  

###### ISSUES ADDRESSED:

Closes 

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
lol you merged all !!! tell me if it works fine bro !

**Comment by dunjeon** [comment]
So far so good =)

**Comment by BarbzYHOOL** [comment]
Do you have a discord for ur repack or something? you could ask players to test the fixes from the PR maybe? like this one I had written how to test it IG

Dunno, just to be sure we don't merge shit

**Comment by dunjeon** [comment]
I don't, but I'll reach out and see what comes back.

**Comment by BarbzYHOOL** [comment]
Also @dunjeon I found a lot of useful SQL to add to AzerothCore (and so your repack)

I think it'd be quite easy to convert compared to the other task we talked about months ago.

You should come to discord!!!

**Comment by dunjeon** [comment]
@BarbzYHOOL  I'm interested, but I have been very busy.

**Pull request merged**
