### PR TITLE
fix error loot altac valley

### PR DESCRIPTION
**Pull request by dunjeon**
## CHANGES PROPOSED:
-  
-  

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
-
-

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
@dunjeon do you test some? if you do plz give feedback !!!

**Comment by BarbzYHOOL** [comment]
also hit me up on discord plz

**Comment by dunjeon** [comment]
@BarbzYHOOL I'm setting up a build to test some PRs, yes.  However, my last few builds have not used anything outside of the master branch -- time being an issue for me.

**Comment by BarbzYHOOL** [comment]
sure but if you or your repack players test, we should gather some feedback? depends on how you proceed etc

**Pull request closed without merging**
